# Define taxonomies for your boat website

# the post for each boat goes here
[vessels]
plural = "vessels"
singular = "vessel"

# general photos go here, along with events like rallies?
[memories]
plural = "memories"
singular = "memory"

# scans and links to other websites etc
[publications]
plural = "publications"
singular = "publication"

# create free-form tags such as “harbour‐work”, “maintenance”, “launch”, “dry-dock”, etc. 
# (You can derive some automatically from filename keywords.)
[tags]
plural = "tags"
singular = "tag"

# slug values: the distinct location words parsed from “Filename”.
# some of these may be harbours, or may be waterways or even just the counties
[ports]
plural = "ports"
singular = "port"
 